language: node_js
node_js:
  - '13.0'

dist: focal
sudo: false

script:
  - npm run test
  - npm run build

#deploy:
#  provider: s3
#  access_key_id: "$AWS_ACCESS_KEY"
#  secret_access_key: "$AWS_SECRET_KEY"
#  bucket: "$AWS_BUCKET"
#  skip_cleanup: true
#  region: "$AWS_REGION"
#  local_dir: public