language: node_js
node_js:
  - '15.4.0'

os: linux
dist: focal

script:
  - npm run test
  - npm run build

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $AWS_BUCKET
  cleanup: false
  region: $AWS_REGION
  local_dir: public