language: node_js
node_js:
  - '16.13.2'

os: linux
dist: focal

script:
  - yarn run test
  - yarn run build

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $AWS_BUCKET
  skip_cleanup: true
  region: $AWS_REGION
  local_dir: public
  on:
    branch: main